---
title: 困難な状況の中でポジティブなところに目を向ける. 
author: 竹林由武
date: '2020-04-03'
slug: 
categories: [mental health]
tags: [IASC]
---


## IASCブリーフィングノートの普及  

コロナ感染拡大が広まる状況下で、人々の不安が高まり、メンタルヘルスの悪化が懸念されています。そのような懸念から、国内外で医療者向け、一般の方向けなど、広くメンタルヘルスケアの啓発がおこなわれています。

私が翻訳に 関わらせてただいた、IASCのブリーフィングノート [「新型コロナウイルス流行時のこころのケア」](https://interagencystandingcommittee.org/system/files/2020-03/IASC%20Interim%20Briefing%20Note%20on%20COVID-19%20Outbreak%20Readiness%20and%20Response%20Operations%20-%20MHPSS%20%28Japanese%29.pdf) もそうした資料の一つです。公開後、色々な施設や個人の方からお問い合わせやコメントをいただいております（自分が関わったものが普及されて嬉しい反面、そこまで感染が広まっている現状が不安で悲しく複雑な気持ちです)。特に要望の多い研修の実施に関して、医大のチームで早急に体制を整えている状況です。


## 寄せられたコメントの紹介

さて、今回のブログでは、このブリーフィングノートをご覧いただいた方が寄せてくれたコメントをご紹介させていただきます。寄せられたコメントは医大チーム内の他の先生に寄せられたものでしたが、その先生から共有いただいたときにとても感動し少しでも多くの人に共有できたらと思い、ブログに掲載する許可をいただきました。コメントをいただいたご本人のご希望でお名前の掲載は控えさせていただきます。

いただいたコメントの内容というのは、ブリーフィングノートの中で明確に示されていることではないのですが、それを読んでメンタルヘルスのために何か子どもとできないかと取り組んでみたこととその結果でした。以下コメントの内容です。

-----

***コロナのポジティブな面を家族で話してみました。以下、しょうもないことですが出たことです。ちょっと気分が浮上しました。*** 


- 清潔さに対する意識が高まった 
- 家族って運命共同体なんだ、ということを実感した  
- 家の中が片付いてきた（することないから）  
- リサイクルにいろいろもっていったら1万円を超えた（貯金）  
- 体温を測ることが多くなったりして、他の病気を見つけやすくなった  
- 久しぶりに友達にばったり道であったら、とてもうれしくて貴重なつながりと感じた  
- まとまった時間ができて普段できないことができる（映画みたり、本を読んだり）  
- 家族で食事をする回数が増えた  
- 家族で行動することが増えた  
- 日本の礼儀のいい面が再認識された（握手やハグじゃなくておじぎとか）  
- 意識が外にむいていたのが内（家族、家、自分、自分の過ごし方など）にいい意味で向いてきている  
- 規則正しい生活（とくに食事）になってきた（外食が減るので）  
- 子どもと初めてマリオ・カートをした（私は娘に負けました）  
- 料理のレパートリーが増えた  
- 子どもが料理をするようになった
- 普段よりちょっとむずかしい本を読むようになった（娘）  
- ニュースの信憑性を見抜く力がついてきた  
- スターウォーズとナウシカを見比べた（先生、すごかったです！連載マンガも）  

-----

以上がいただいたコメントです。コメントの多くはお子さんが発見してくれたことだそうで、子どもってすごいなぁ、大変な中で逆に大人の気持ちが救われているんだなぁと、最近親になった私はしみじみと感じてしまいました。

### 困難な状況下でのポジティブな感情調整

いただいたコメントには、大変な状況であっても、それ以前にはなかった良い変化もおきているとことに気づいたといった様子が伺えます。こうした変化は、心理学においては、レジリエンス (resilience)[^1]や外傷後成長 (post-traumatic growth[^2])などの概念に関連した研究を通じて、困難な状況を体験した人々の精神的健康の維持/回復に重要であることが指摘されてきました。  

[^1]: Bonanno, G. A. (2004). Loss, trauma, and human resilience: Have we underestimated the human capacity to thrive after extremely aversive events?. American psychologist, 59(1), 20.

[^2]: Tedeschi, R. G., & Calhoun, L. G. (1996). The Posttraumatic Growth Inventory: Measuring the positive legacy of trauma. Journal of traumatic stress, 9(3), 455-471.

国立精神神経医療研究センターの山口慶子先生, 伊藤正哉先生と一緒に取り組んだ大学生を対象としたアンケート調査[^3]においても、困難な状況下でポジティブ感情を維持するような感情の調整の仕方が、1ヶ月後の抑うつ症状を説明することが示されています[^4]  

[^3]: Yamaguchi, K., Ito, M., & Takebayashi, Y. (2018). Positive emotion in distress as a potentially effective emotion regulation strategy for depression: A preliminary investigation. Psychology and Psychotherapy: Theory, Research and Practice, 91(4), 509-525.

[^4]:ただし2時点のみの調査で単一の研究による知見であり、大学生を対象にした調査結果でもあるため、本結果がどこまで頑健で一般化可能であるかはさらなる検証が必要です。



この研究で扱われたポジティブな感情調整は以下の質問項目への回答に基づいて得点化されました。

- 暖かい気持ちを思い出して、苦しい状況を乗り越えられる。  

- つらいときでも大切な人や言葉を思い出して暖かい気持ちを感じられる。  

- 不安な気持ちに襲われても、自分を大切にできる  

- 感情に圧倒されても、心の中で安心を取り戻すことができる  

- 心の中の暖かみのある気持ちにふれて、落ち着くことができる  

- 気持ちに圧倒されてしまうと、決して暖かい気持ちにはなれない (逆転項目)  

- 不安なときでも、自分で自分のこころを落ち着かせることができる  

- つらい気持ちのとき、大切な人物や言葉などまったく思い出せなくなる (逆転項目)

- 心が苦しい気持ちになっていても、安心できることを思い出せる  

- 大変なときに、自分を勇気づけ励ましてくれる言葉や人物を思い出せる


先行きが見えない不確実な状況で気持ちが不安に支配されがちな状況ですが、こんなときこそ、些細な良い気持ち、幸せな気持ちに留まることができるよう生活の工夫をすることが精神的な健康を維持するために役立つかもしれません。

困難な状況を乗り切るための少しのヒントになれば幸いです。



